# Generated by Django 3.2 on 2023-08-23 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20230822_1707'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='amount',
            field=models.CharField(default=0, max_length=16),
        ),
        migrations.AddField(
            model_name='user',
            name='attempts',
            field=models.CharField(default=0, max_length=16),
        ),
    ]
